[package]
name = "actix-mixed-playground"
version = "0.1.0"
authors = ["Sam Stelfox <sstelfox@bedroomprogrammers.net>"]

[dependencies]
actix = "0.5"
actix-web = "0.6"
dotenv = "0.13"
env_logger = "0.5"
futures = "0.1"
log = "0.4"
rand = "0.5"

[dev-dependencies]
tokio-core = "0.1"
